---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: clustersql
  name: clustersql
  namespace: kube-system
spec:
  ports:
  - name: "mysql"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: clustersql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clustersql
  name: clustersql
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clustersql
  template:
    metadata:
      labels:
        app: clustersql
    spec:
      containers:
      - image: adalrsjr1/clustersql
        imagePullPolicy: IfNotPresent
        name: clustersql
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
      restartPolicy: Always
---
